celebrity = input("Enter favorite celebrity name: ")
animal = input("Enter an animal: ")
parent = input("Enter the name of one of your parents: ")
furniture = input("Enter a piece of furniture in your house: ")
activity = input("Enter an activity that you dislike: ")
object = input("Enter an object nearest you: ")
print(f"Hi my name is {celebrity}. ")
print(f"In my free time I enjoy eating {animal}. ")
print(f"My favorite food, however is {parent}. ")
print(f"When I am not eating {parent}, I like chomping on {furniture}. ")
print(f"When I am not chomping on {furniture}, I like {activity}. ")
print(f"Finally, I live in a small {object}.")
